// LABELS System for multilingual interface
export const LABELS: Record<string, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    explore: "Explore",
    create: "Create",
    profile: "Profile",
    settings: "Settings",
    capsules: "Capsules",
    reels: "Reels",
    truth_score: "Truth Score",
    emotional_resonance: "Emotional Resonance",
    listen_summary: "Listen to Summary",
    translate: "Translate",
    mint_nft: "Mint NFT",
    upload: "Upload",
    analyze: "Analyze",
    complete: "Complete",
  },
  es: {
    dashboard: "Tablero",
    explore: "Explorar",
    create: "Crear",
    profile: "Perfil",
    settings: "Configuración",
    capsules: "Cápsulas",
    reels: "Reels",
    truth_score: "Puntuación de Verdad",
    emotional_resonance: "Resonancia Emocional",
    listen_summary: "Escuchar Resumen",
    translate: "Traducir",
    mint_nft: "Acuñar NFT",
    upload: "Subir",
    analyze: "Analizar",
    complete: "Completar",
  },
  ar: {
    dashboard: "لوحة التحكم",
    explore: "استكشاف",
    create: "إنشاء",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    capsules: "كبسولات",
    reels: "ريلز",
    truth_score: "نتيجة الحقيقة",
    emotional_resonance: "الرنين العاطفي",
    listen_summary: "استمع للملخص",
    translate: "ترجم",
    mint_nft: "سك NFT",
    upload: "رفع",
    analyze: "تحليل",
    complete: "مكتمل",
  },
  zh: {
    dashboard: "仪表板",
    explore: "探索",
    create: "创建",
    profile: "个人资料",
    settings: "设置",
    capsules: "胶囊",
    reels: "短视频",
    truth_score: "真实度评分",
    emotional_resonance: "情感共鸣",
    listen_summary: "听摘要",
    translate: "翻译",
    mint_nft: "铸造NFT",
    upload: "上传",
    analyze: "分析",
    complete: "完成",
  },
};

export function getLabel(key: string, language: string = "en"): string {
  return LABELS[language]?.[key] || LABELS.en[key] || key;
}
